### ISSUE TITLE
i can't proceed

### ISSUE THREAD

**Issue by IceCube02** [boxsux/reactionfirst-bot#3]
![image](https://user-images.githubusercontent.com/117892140/217831077-4adf3d6e-eb34-4868-9e65-1ce1ace272f0.png)

**Comment by angelyurii** [comment]
This is because you did not specify a bot token. Please read [step 0 of the wiki](https://github.com/zyxophobia/reactionfirst-bot/wiki/Deploying-locally#0-set-up-the-bot) to get your token, and [step 3](https://github.com/zyxophobia/reactionfirst-bot/wiki/Deploying-locally#3-create-the-configuration-file) to set up the configuration file.

**Comment by IceCube02** [comment]
![image](https://user-images.githubusercontent.com/117892140/217832790-d41f2e87-95a6-477f-9f8d-ae85b9ad2283.png)
is this the right code??

**Comment by angelyurii** [comment]
Almost! The code in the wiki is something you would paste into your _terminal_.

Remove lines 1 and 4 in that file (the lines with EOF in them — remove the **full line**), then you should be fine.

**Comment by IceCube02** [comment]
![image](https://user-images.githubusercontent.com/117892140/217834611-893ad516-60ce-4139-8e08-bf239457d077.png)
like this?

**Comment by angelyurii** [comment]
Yes! All you need to do is rename that file to `.env` and you'll be all set.

**Comment by IceCube02** [comment]
Thanks
